-- The "current production" schema.
CREATE TYPE order_status AS ENUM ('pending', 'shipped');
CREATE TYPE payment_method AS ENUM ('card', 'cheque', 'cash');

CREATE TABLE customers (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email   varchar(120) NOT NULL,
  country char(2)
);
CREATE UNIQUE INDEX customers_email_idx ON customers (email);

CREATE TABLE orders (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES customers (id),
  status      order_status NOT NULL DEFAULT 'pending',
  payment     payment_method NOT NULL DEFAULT 'card',
  total_cents integer NOT NULL CHECK (total_cents >= 0)
);

CREATE TABLE legacy_audit (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payload text
);
