-- The desired schema: a new enum label, a new table with a foreign key,
-- a widened column, and a table that should go away.
CREATE TYPE order_status AS ENUM ('pending', 'shipped', 'refunded');
-- 'cheque' is retired: Postgres has no DROP VALUE, so this forces a type rebuild.
CREATE TYPE payment_method AS ENUM ('card', 'cash');

CREATE TABLE customers (
  id      integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email   text NOT NULL,
  country char(2),
  vip     boolean NOT NULL DEFAULT false
);
CREATE UNIQUE INDEX customers_email_idx ON customers (email);

CREATE TABLE orders (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id integer NOT NULL REFERENCES customers (id),
  status      order_status NOT NULL DEFAULT 'pending',
  payment     payment_method NOT NULL DEFAULT 'card',
  total_cents integer NOT NULL CHECK (total_cents >= 0)
);

CREATE TABLE shipments (
  id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id integer NOT NULL REFERENCES orders (id),
  carrier  text NOT NULL,
  shipped_at timestamptz
);
CREATE INDEX shipments_order_idx ON shipments (order_id);
